name: cta4j Java SDK – PR Build & Test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "25"
          cache: "maven"
      - name: Build with Maven
        run: mvn -B package --file pom.xml
